name: RSA256_build

on: push

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_cmake:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/yodalee/rsa256
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Running vint/varray/vstruct unittests
      run: ${{github.workspace}}/build/test/test_dtype

    - name: Running RSA unittests
      run: ${{github.workspace}}/build/cmodel/test_rsa_cmodel

    - name: Running Verilog RSATwoPowerMod
      run: ${{github.workspace}}/build/verilog/VRSATwoPowerMod

    - name: Running Verilog RSAMontgomery
      run: ${{github.workspace}}/build/verilog/VRSAMontgomery

    - name: Running Verilog RSA
      run: ${{github.workspace}}/build/verilog/VRSA
