name: RSA256_build

on: push

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_cmake:
    runs-on: ubuntu-22.04

    steps:
    - name: Install Required Package
      run: sudo apt update &&
        sudo apt install -y libgtest-dev libgmp-dev build-essential cmake libsystemc-dev libgtest-dev
        python3 wget autoconf perl flex bison zlib1g-dev libfl-dev

    - uses: actions/checkout@v3

    - name: Run install_verilator.sh
      run: mkdir custom_package && cd custom_package && ${{github.workspace}}/docker/install_verilator.sh
      shell: bash
      env:
        THE_PREFIX: /usr/
        SUDO: sudo

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Running vint unittests
      run: ${{github.workspace}}/build/test/test_verilog_int

    - name: Running random generator unittests
      run: ${{github.workspace}}/build/test/test_abstract_random

    - name: Running RSA unittests
      run: ${{github.workspace}}/build/cmodel/unit_test
